CREATE TABLESPACE good
DATAFILE 'C:\APP\EUNBI\PRODUCT\18.0.0\ORADATA\XE\good.DBF'
SIZE 300M AUTOEXTEND ON NEXT 30M;

ALTER SESSION SET "_oracle_script" = true;

CREATE USER james
IDENTIFIED BY goodman
DEFAULT TABLESPACE good
TEMPORARY TABLESPACE temp;

--1-3 사용자 권한을 부여
GRANT RESOURCE, CREATE SESSION, CREATE VIEW, CREATE SYNONYM TO james;

