CREATE TABLE PC_BOARD(
    SEQ NUMBER(7) PRIMARY KEY,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENTS CLOB,
    READ_CNT NUMBER(6) DEFAULT 0,
    REG_DT DATE DEFAULT SYSDATE,
    REG_ID VARCHAR2(20),
    MOD_DT DATE DEFAULT SYSDATE,
    MOD_ID VARCHAR2(20)
);