SELECT SYSDATE,
        TO_CHAR(SYSDATE,'MM') AS "MM",
        TO_CHAR(SYSDATE,'MON','NLS_DATE_LANGUAGE=KOREAN') AS "KOREAN",
        TO_CHAR(SYSDATE,'MON','NLS_DATE_LANGUAGE=JAPANESE') AS "JAPANESE",
        TO_CHAR(SYSDATE,'MON','NLS_DATE_LANGUAGE=ENGLISH') AS "ENGLISH",
        TO_CHAR(SYSDATE,'MONTH','NLS_DATE_LANGUAGE=ENGLISH') AS "ENGLISH_MONTH"
FROM dual
;