--TEMP테이블생성
CREATE TABLE TEMP(
    COL1 VARCHAR2(20),
    COL2 VARCHAR2(20)
);

--TEMP테이블에 SELECT권한을 ORCLSTUDY에 부여
GRANT SELECT ON TEMP TO ORCLSTUDY;

--TEMP테이블에 INSERT권한을 ORCLSTUDY에 부여
GRANT INSERT ON TEMP TO ORCLSTUDY;

--SELECT, INSERT권한을 한꺼번에 부여
GRANT SELECT, INSERT ON TEMP TO ORCLSTUDY;

SELECT * FROM temp;