DROP INDEX PK_BOARD;

/* 게시판 */
DROP TABLE BOARD 
	CASCADE CONSTRAINTS;

/* 게시판 */
CREATE TABLE BOARD (
	SEQ NUMBER(7) NOT NULL, 
	TITLE VARCHAR2(200 BYTE) NOT NULL, 
	CONTENTS CLOB, 
	READ_CNT NUMBER(7) DEFAULT 0, 
	REG_DT DATE,
	REG_ID VARCHAR2(20 BYTE),
	MOD_DT DATE, 
	MOD_ID VARCHAR2(20 BYTE) 
);

COMMENT ON TABLE BOARD IS '게시판';

COMMENT ON COLUMN BOARD.SEQ IS '순번';

COMMENT ON COLUMN BOARD.TITLE IS '제목';

COMMENT ON COLUMN BOARD.CONTENTS IS '내용';

COMMENT ON COLUMN BOARD.READ_CNT IS '조회수';

COMMENT ON COLUMN BOARD.REG_DT IS '등록일';

COMMENT ON COLUMN BOARD.REG_ID IS '등록자';

COMMENT ON COLUMN BOARD.MOD_DT IS '수정일';

COMMENT ON COLUMN BOARD.MOD_ID IS '수정자';

CREATE UNIQUE INDEX PK_BOARD
	ON BOARD (
		SEQ ASC
	);

ALTER TABLE BOARD
	ADD
		CONSTRAINT PK_BOARD
		PRIMARY KEY (
			SEQ
		);