--p.358 Q3.
CREATE TABLE deptseq
AS
SELECT *
FROM dept
;

SELECT * FROM deptseq;

CREATE SEQUENCE seq_deptseq
INCREMENT BY 1
START WITH 1
MAXVALUE 99
MINVALUE 1
NOCYCLE
NOCACHE;

INSERT INTO deptseq VALUES (SEQ_DEPTSEQ.nextval,'DATABASE','SEOUL');
INSERT INTO deptseq VALUES (SEQ_DEPTSEQ.nextval,'WEB','BUSAN');
INSERT INTO deptseq VALUES (SEQ_DEPTSEQ.nextval,'MOBILE','ILSAN');
COMMIT;
SELECT * FROM deptseq;